### ISSUE TITLE
Release 0.4.0 - Backoffice

### ISSUE THREAD

**Issue by cristiandouce** [DemocracyOS/democracyos#243]
The main feature added to this release is the administration module. Allowing only certain users to ADD, EDIT, DELETE laws.

Features:
- [x] Simple layout at `/admin` #240
- [x] Restrict allowed users via config as a quick solution #241
- [x] Laws `CRUD` pages. #242

cc @gvilarino @slifszyc
